<script lang="ts">
	import { page } from '$app/state';
	import type { Snippet } from 'svelte';

	let { children }: { children: Snippet } = $props();

	// Safely access metadata from the page data, defaulting to an empty object to prevent errors.
	const metadata = $derived(page.data.metadata || {});
</script>

<svelte:head>
	<title>{metadata.title ?? 'About Carbonatik'}</title>
	<meta name="description" content={metadata.description ?? 'Learn more about Carbonatik.'} />
	{#if metadata.keywords}
		<meta name="keywords" content={metadata.keywords} />
	{/if}
</svelte:head>

<article class="prose prose-invert max-w-4xl mx-auto px-4 py-16 sm:py-24">
	{@render children()}
</article>

<style lang="postcss">
	/* Reference the main app.css to use @apply and get theme context */
	@reference '../../app.css';

	/*
	  Use :global() to style the elements generated by mdsvex,
	  which are not directly visible to the Svelte compiler.
	*/
	:global(.prose) {
		@apply text-neutral-400 font-light;
	}

	:global(.prose h1, .prose h2, .prose h3) {
		@apply text-neutral-100 font-semibold tracking-tight;
	}

	:global(.prose strong) {
		@apply font-semibold text-neutral-200;
	}

	:global(.prose a) {
		@apply text-sky-400 no-underline hover:underline;
	}

	/* Custom styles for components embedded in Markdown */
	:global(.leadership-grid) {
		@apply grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-6 my-10;
	}
	:global(.leadership-grid .name) {
		@apply font-bold text-lg text-neutral-200;
	}
	:global(.leadership-grid .title) {
		@apply text-sm text-neutral-500;
	}
	:global(.contact-card) {
		@apply mt-16 rounded-lg border border-neutral-800 bg-neutral-900 p-8 text-center;
	}
	:global(.contact-card h3) {
		@apply text-2xl font-bold text-neutral-100;
	}
	:global(.contact-card p) {
		@apply my-4 max-w-2xl mx-auto;
	}
	:global(.contact-card .contact-details) {
		@apply flex flex-col sm:flex-row gap-4 sm:gap-8 justify-center text-sky-400 font-medium;
	}
	:global(.contact-card .contact-details a:hover) {
		@apply underline;
	}
</style>